version: '3.8'
services:
  db:
    image: postgres:15
    env_file:
      - .env           # carrega as variáveis abaixo
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
