"""Add Questionario relationship

Revision ID: 14b5c45e4801
Revises: c7678c8dc300
Create Date: 2025-06-12 00:30:46.875382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b5c45e4801'
down_revision: Union[str, None] = 'c7678c8dc300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionarios', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('relatorios', 'paciente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('relatorios', 'nutricionista_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relatorios', 'nutricionista_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('relatorios', 'paciente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questionarios', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
