"""add questionnaire answers

Revision ID: 174d3f41da79
Revises: 2e939a941fff
Create Date: 2025-07-02 15:31:49.267706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174d3f41da79'
down_revision: Union[str, None] = '2e939a941fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['questionnaire_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['option_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_answers_id'), 'questionnaire_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnaire_answers_id'), table_name='questionnaire_answers')
    op.drop_table('questionnaire_answers')
    # ### end Alembic commands ###
