"""initial migration

Revision ID: 65f3ae5b6002
Revises: 2af417390842
Create Date: 2025-06-25 23:27:27.665540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f3ae5b6002'
down_revision: Union[str, None] = '2af417390842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nutricionista_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['nutricionista_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'nutricionista_id')
    # ### end Alembic commands ###
