"""initial migration

Revision ID: d0bab24d1d19
Revises: 65f3ae5b6002
Create Date: 2025-06-25 23:50:47.976025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bab24d1d19'
down_revision: Union[str, None] = '65f3ae5b6002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['questionnaire_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_responses_id'), 'questionnaire_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnaire_responses_id'), table_name='questionnaire_responses')
    op.drop_table('questionnaire_responses')
    # ### end Alembic commands ###
